# Admissions

## Prospective Students

Please consider watching this webinar recording that provides an introduction to graduate school in general and information about our specific programs. The webinar also includes a Q&A with current graduate students.


<iframe id="kaltura_player"
  src="https://cdnapisec.kaltura.com/p/505811/embedPlaykitJs/uiconf_id/55068052?iframeembed=true&entry_id=1_esf7ue9c&config%5Bprovider%5D=%7B%22widgetId%22%3A%221_mjy4jcdo%22%7D&config%5Bplayback%5D=%7B%22startTime%22%3A0%7D"
  style="width: 640px; height: 360px; border: 0;"
  allowfullscreen
  allow="autoplay *; fullscreen *; encrypted-media *"
  sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation"
  title="Fall 2025 College of Life Sciences and Agriculture (COLSA) Grad Open House">
</iframe>

### Do I need to contact prospective advisors before applying?

Yes! If you are interested in a MS or PhD program within UNH’s Department of Biological Sciences (three distinct programs: Integrative Biology, Marine Biology, Neuroscience & Behavior), you must contact potential thesis mentors (professors) before applying to our programs. You can find a [directory of relevant mentors on the faculty webpage](https://colsa.unh.edu/biological-sciences/people) and under the [individual program descriptions](https://colsa.unh.edu/biological-sciences/academics). 

It is never too early to contact potential thesis mentors, but we suggest contacting them between August and October of the year before you expect to start your degree (for example, contact a mentor in September 2025 if interested in applying by January 2026 for full consideration to begin as a graduate student in Fall 2026). However, you should never be afraid to reach out to a prospective mentor as graduate opportunities can open throughout the year.

### How do I contact potential advisors? 

After identifying professors whose interest align with yours, send them an email to introduce yourself and your interests. This email should contain the following:

    A brief introduction of who you are and your current status
    Your interests broadly
    Why you are interested in this professor’s work and how it aligns with your own interests
    Attachments of CV or resume, and unofficial transcripts

Still intimidated? Use the text below labeled “Email Template” to help you contact a professor.

### Can I contact more than one professor in the Department of Biological Sciences or at UNH? 

Absolutely! Graduate positions are very competitive, and often a professor can only take on one or two students each year (if any). Thus, it’s important to contact as many professors as possible, provided that their research aligns with your interests. You can let professors know who else you are contacting within the department or university when you contact them (see template below).

### What if I don’t get a response? 

Try again! Professors are very busy, and can receive hundreds of emails a day. Sometimes this results in slow reply times, or simply emails getting missed or lost. Wait at least a week, and then try to send again. If after three tries you still do not get a response, this likely means the professor is not taking on any graduate students in the near future.

### Are there fee waivers?

You might be eligible for a fee waiver after finding a prospective advisor that is open to supporting your application. 

I have a prospective advisor who has encouraged me to apply. What do I do now?

On the web pages for each program, you’ll see details on how to apply (dates, letters of recommendation needed, etc). 

### What funding is available for graduate students?

When you meet with a potential advisor, they’ll review available funding options with you. In most cases, we only admit students if we can support them financially (which typically includes waivers for health insurance and tuition) throughout their degree. Funding typically comes from a mix of graduate assistantships. Some students are supported through their advisor’s research grants, while many serve as teaching assistants in our biology labs (to be fully considered for assistantships, apply by the January deadline). The university also offers a limited number of fellowships, though these are usually awarded to current students rather than incoming ones. Additionally, some international students receive funding from their home governments or external fellowships such as those from the National Science Foundation or private foundations. Professor White maintains a list of some of these external fellowships. 

### What are the requirements of each program?

Each program differs a bit in their requirements (e.g., coursework requirements), so be sure to look through the individual program pages.

### Other general tips and advice for applying to graduate school:

Take time to think about why you want to go to graduate school and conduct research (and communicate this clearly when reaching out to prospective mentors). Before contacting prospective mentors, take some time to learn about their research (either via webpages, their publications, or other resources). Get help from advisors, your university career centers, and others for updating your resume or CV, ensuring that you highlight any research or scientific experiences, important courses taken, skills, and awards received.

### Email Template

If you are potentially interested in working with one or more professors towards a MS or PhD in Biological Sciences at the University of New Hampshire, you can use this template email to introduce yourself to these potential advisors.

Please note that you should contact each professor individually (it’s okay to contact more than one faculty member in our department!); individualize your responses to each professor, particularly paragraphs #2 and #3). Also know that this is simply a template; prospective students do not need to follow these instructions exactly when reaching out to prospective mentors. We just hope this helps you get started and give you confidence in contacting faculty!

Dear Dr. [insert professor’s full name here]:

Paragraph 1: Introduce yourself! State your name, educational status and history (including GPA and major and/or degree. If you have graduated, include when you graduated and your current position.), and what semester and year you are aiming to start your graduate studies.

Paragraph 2: Discuss your relevant qualifications and experience that make you an ideal candidate for our graduate program. This may include specific skills you have, research experiences, internships, publications or presentations, and relevant coursework.

Paragraph 3: Describe your specific interests within the field of Biological Sciences? How do these interests align with this professor’s work? What about this professor’s work excites you? Be specific when possible, demonstrating your own efforts to understand this professor’s research.

Thank you for your time in reading this email and your consideration. I have attached my [resume/CV; make sure to attach!] and unofficial transcripts [attach]. I would enjoy an opportunity to chat with you further about potential opportunities as a graduate student in your research group.

Sincerely,

[Insert your full name here]
