# Onboarding {#onboarding}

## Essential Information for New Graduate Students  


### Key Items (Complete ASAP)

#### Student ID
- Respond to the message sent from *Online Photo* to your UNH email address  
- Upload your photo and pick up your ID on campus  
- More information: https://www.unh.edu/dining/dining-id-parking-services/unh-id-cards  
- Help: (603) 862-1821 or ID.Office@unh.edu

#### UNH Email
- Used for all official UNH communication  
- Instructions: https://unh.edu/it/kb/article/accessing-student-email-wildcats-mail.html  
- Includes steps to link other UNH systems (e.g., MyCourses/Canvas)

#### Contacts and Department Access
- Advisor: Contact ASAP  
- Department faculty list: https://colsa.unh.edu/biological-sciences/people  
- Lisa Buchalski (Administrative Coordinator)  
  - lisa.buchalski@unh.edu | 603-862-3626  
- Elizabeth Harvey (Associate Chair)  
  - elizabeth.harvey@unh.edu | 603-862-3418  

#### Office Access and Keys
- Contact Lisa Buchalski (lisa.buchalski@unh.edu, 603-862-3626)



### Orientation (Last Week of August)

#### Required Orientation Events
- Watch for an email from Lisa Buchalski with details on mandatory events  
- Incoming graduate students typically attend:
  - Department orientation  
  - UNH Graduate School orientation  
  - TA training (if applicable)  
  - Safety training  
- Attendance is expected for all mandatory sessions



### Registration (Last Week of August)

#### Registering for Classes
- Register prior to the start of classes  
- All incoming graduate students must enroll in BIOL 901  
- Discuss additional first-semester courses with your advisor


### Health Insurance and Medical Records (By ~September 1)

#### Student Health Benefits Plan (SHBP)
- Submit physical and immunization records online  
- SHBP waiver/enrollment period: June 16 – September 16  
  - All full-time students must take action  
- Key links:
  - SHBP overview: http://www.unh.edu/health/shbp  
  - Incoming student health requirements: http://www.unh.edu/health/incoming-students  
  - Insurance provider: https://wellfleetstudent.com/

#### Questions or Assistance
- UNH.SHBP@unh.edu  
- Greg Turcotte, Business Manager, Health & Wellness  
  - gregory.turcotte@unh.edu | 603-862-2855  
- Cindy McGahey, Director of Finance & Administration, Health & Wellness  
  - Cindy.McGahey@unh.edu | 603-862-2853  

---

### Additional Logistics and Resources

#### Online Resources for New Graduate Students
- UNH Graduate School (new student info): https://gradschool.unh.edu/enroll.php#admin  
- Biological Sciences Graduate Program documents and handbook:  
  https://colsa.unh.edu/biological-sciences/key-documents  

#### Support for International Students
- Office of International Students & Scholars: https://www.unh.edu/global/international-students  
- Contact: oiss@unh.edu

#### Parking and Transportation
- Parking permits (commuter students): http://www.unh.edu/transportation/parking  
- Wildcat Transit and transportation info: http://www.unh.edu/transportation/wildcat-transit  

#### Emergency Alerts
- Automatic notifications for weather, safety, and local emergencies:  
  https://www.getrave.com/login/unh

#### UNH Calendar
- https://calendar.unh.edu






## Being productive and sane 

- [Book - Deep Work by Cal Newport](https://www.amazon.com/Deep-Work-Focused-Success-Distracted/dp/1455586692). All of his books are great, especially *So Good They Can't Ignore You*, *A World Without Email*, and *Slow Productivity*
- [Book - How to Write A Lot by Paul Silvia](https://www.amazon.com/How-Write-Lot-Practical-Productive/dp/1591477433)
- [Book - A Field Guide to Grad School by Jessica McCrory Calarco](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school)
- [Book - Pasteur’s Quadrant by Donald Stokes](https://www.brookings.edu/books/pasteurs-quadrant/) and a [follow up article on the topic](https://academic.oup.com/pnasnexus/article/1/3/pgac092/6615485)
- [Good collection of book recommendations here](https://fromphdtolife.com/resources/recommended-reading/)


## Being a mentee or mentor 

- [How to manage your supervisor](https://www.science.org/content/article/how-get-what-you-need-your-phd-or-postdoc-supervisor)


## Required training

The [UNH Responsible Conduct of Research and Scholarly Activity (RCR)](https://www.unh.edu/research/research/compliance-safety/responsible-conduct-research-scholarly-activity/rcr-training-unh) Committee announces the availability of training in the ethical and responsible conduct of research.
 
The training fulfills:
The National Science Foundation (NSF) mandate that all postdoctoral researchers, and undergraduate and graduate students supported by NSF to conduct research on proposals submitted on or after January 4, 2010, receive appropriate training in the ethical and responsible conduct of research. Effective with proposals submitted to NSF on or after 7/31/2023, faculty and other senior personnel will be required to complete responsible and ethical conduct of research training. Click here for details about UNH's RCR training requirements for the different audiences. 
The United States Department of Agriculture (USDA) National Institute of Food and Agriculture (NIFA) RCR requirement. Click here for details about UNH's RCR training requirements for different audiences.
 
This training opportunity involves two components:
Completion of a web-based RCR course (available here), followed by
Participation in a seminar on Friday, February 27, 2026, 1:10 – 4:00 pm via Zoom.
Modules must have been completed prior to participation in the seminar. Successful completion of the training requires completion of both components.

Registration for the seminar is required: Individuals must register for the seminar by Thursday, February 19, 2026. Registration information is available [here](https://www.unh.edu/research/research/compliance-safety/responsible-conduct-research-scholarly-activity/rcr-training-unh). 
 
This training is open to any member of the UNH community. While it is primarily directed at postdoctoral researchers, graduate students, and undergraduate students, faculty and staff are invited to participate.
 
For more information, please contact [Julie Simpson in Research Integrity Services](https://www.unh.edu/research/research/compliance-safety/responsible-conduct-research-scholarly-activity/rcr-training-unh). Thank you.









