# PhD Neuroscience & Behavior

## Program Description 


## Learning Outcomes


## Program Requirements and Timeline

### Committee

Committees are comprised of five people: your advisor, another DBS faculty member, and three additional people. At least two committee members must be external to DBS. Members of UNH must be part of the graduate faculty (which is an easy application if they aren't already graduate faculty). For non-UNH members, you must submit a CV on their behalf. All committee members should have a PhD or commensurate experience.


### Credit Requirements

The M.S. degree requires completion of a minimum of 30 credits, 6-¬10 of which are earned for thesis research (BIOL 899 Master's Thesis ). 

There is no specific credit requirement for the Ph.D., though students must meet curriculum requirements.

Up to 8 graduate credits from another institution may be transferred, provided the credits were not counted toward another degree, and the course grade was a B or higher. Petitions requesting transfer credit must be supported by the advisor and graduate committee, and approved by the UNH Graduate School.
Students admitted via the Accelerated Master's (AM) process may apply up to 12 credits of prior upper-level UNH coursework in accordance with AM policies.

The level of the courses taken to meet registration requirements is not specified. However, taking non-graduate classes does not move one towards degree completion, so taking undergraduate classes is not a common practice. A grad student cannot petition to take a 500-level course, however 500-level courses can be audited by graduate students with the cost of the course at the expense of the graduate student.

Students should discuss with their advisor and committee which courses will be most useful, and what course load makes sense in light of specific research and assistantship obligations (for example, an intense field season). 

How many credits to take, and financial implications: 

Graduate students are normally required to maintain continuous enrollment each Fall and Spring semester by registering for courses, research (Grad 900/BIOL 999), or continuing enrollment (Grad 800) (see below for distinctions). Students who don’t register for the Fall and Spring semesters will have their degree status discontinued.

Graduate students registered for 9 or more credits, Master's Continuing Research (Grad 900), or Doctoral Research (999) are classified as full-time students. Students holding assistantship appointments are also considered full time and must register for a minimum of 6 credits, or Doctoral Research (999) each semester. Students registered for Continuing Enrollment (GRAD 800) are not eligible to hold an appointment. For details, please see the Graduate School website (https://catalog.unh.edu/graduate/course- descriptions/grad).

Students on assistantships (TA or RA) pay reduced mandatory fees (fee information: https://www.unh.edu/business-services/tuitgrad); this benefit applies no matter how many credits you’re taking. Tuition is commonly waived or covered for students on TA or RA appointments; however, mandatory fees remain the responsibility of the student. Students on assistantship in the spring semester can have tuition waived for summer courses offered by the Graduate School (GRAD prefix).

Students enrolled for more than 16 credits pay additional tuition based on the number of additional credits (https://www.unh.edu/business-services/tuitgrad). 

Doctoral students who have advanced to candidacy may petition each semester to waive fees if they meet the specified conditions (https://catalog.unh.edu/graduate/general-information/fees-financial-support/).

Tuition and fee information from UNH Business Services is available at https://www.unh.edu/business-services/tuitgrad; Graduate School information about fees and financial support is at  https://catalog.unh.edu/graduate/general-information/fees-financial-support/ .

Which courses count:

Graduate courses are numbered 800- or 900-level. Course descriptions can be found in the online Graduate Course Catalog (https://catalog.unh.edu/graduate/). If there is a graded option, graduate courses may not be taken Pass/Fail.

Graduate credit for 700-level courses: 700-level courses are advanced undergraduate courses. In rare cases graduate degree students may petition to earn graduate credit for up to 12 credits in 700-­level courses, provided the credits are taken in a program other than the one in which the student is seeking the degree and provided such courses are approved by the student's adviser, graduate program coordinator, and the dean of the Graduate School. Such courses must be taken for a letter grade. Petitions must include what additional requirements or expectations will be required of the student to make the course a graduate level experience.  Petition requests must be made prior to enrolling in the course and are not guaranteed.  Petition forms are available at https://gradschool.unh.edu/academics/forms-policies.

Undergraduate courses below 700-level: While taking non-graduate classes is generally discouraged, in some cases, graduate students may need background or training that can best be obtained by taking an upper-level undergraduate class, if no equivalent course is offered at the graduate level. Undergraduate level courses taken by graduate students are billed at the graduate rate, must be taken for a letter grade, and are subject to the Graduate School’s failing grade policy. Courses taken below the 700-level cannot count as graduate credit.

Audits: Graduate students may audit courses with the approval of their advisor and the instructor. Credits for an audited course in which a graduate student is formally enrolled may be counted toward enrollment requirements for appointments and assistantships. (Note that tuition for audited courses is the same as for credit courses.)

Graduate credit from another institution: Students can request to transfer up to 8 credits of graduate credit from another school, provided the credits were not counted toward another degree, and the grade was at least a B. The transfer request form is available at (https://gradschool.unh.edu/academics/forms-policies). 

Where to find enrollment policy, course and registration information:
• Graduate School enrollment policies and petition forms: https://gradschool.unh.edu/academics/forms-policies
• the UNH Course Search Form searches all courses (grad and undergrad) (https://courses.unh.edu/)https://courses.unh.edu/
• descriptions of graduate courses are in the online catalog https://catalog.unh.edu/graduate/
• registration information and deadlines are posted at the Graduate School website https://gradschool.unh.edu/graduate-student-resources 


### Change of Degree Status, M.S. to Ph.D. Enrollment

M.S. graduates normally go elsewhere for further study or for employment after completing their thesis. However, students enrolled for an M.S. degree may petition the Graduate School to continue for the Ph.D. after receipt of the M.S. or, rarely, to convert to Ph.D. enrollment without first completing the M.S. If a student wishes to convert from M.S. to Ph.D., the advisor will convene a meeting of the DBS GPC and the student's Master’s Thesis Committee to consider the application. If the application has departmental support, a "change of degree" form is then completed and submitted for Graduate School approval (https://gradschool.unh.edu/academics/forms-policies).

Admission to Ph.D. enrollment should not be considered automatic on completion of the M.S., and conversion from M.S. directly to Ph.D. enrollment is done only in extraordinary circumstances. Conversion, when appropriate, should occur no later than the beginning of the third semester of enrollment.

Students who change to a Ph.D. program (and have not already done so) are required to attend the Responsible Conduct of Research Training. Further information is available at https://www.unh.edu/research/rcr-training-unh.


### Research Proposal
Ph.D. students present and defend their formal research proposal to their Guidance Committee in order to be advanced to candidacy, normally in the second or third year. However, a solid draft of the proposal should be shared with the committee by the end of the second semester, and presented in seminar form at least to the committee, and preferably for a wider (public) audience.

Please contact individual Program Coordinators to find guidance in terms of proposal length and format.

Ph.D. qualifying exam and advancement to candidacy

Following approval of the research proposal by their committee, students who wish to be admitted to doctoral candidacy must pass a formal qualifying examination that assesses both broad basic knowledge of the student’s field, and topics central to the project. The student is responsible for scheduling both parts of the exam; plan well ahead to account for committee members’ travel plans, sabbaticals, etc. The written portion of the qualifying exam should be taken no later than the end of the fifth semester, though it may be delayed beyond that point if necessary.  The oral portion of the exam follows successful completion of the written part, usually within a few weeks. 

Student’s should contact their respective degree programs to be provided specific details regarding the procedure of both the written and oral comprehensive exam.

When the student has passed both parts of the qualifying exam, the advisor will inform the Graduate School and recommend that the student be advanced to candidacy in the Ph.D. degree program by submitting the appropriate form (https://gradschool.unh.edu/academics/forms-policies) . At this point, the student’s Doctoral Dissertation Committee will be nominated using the Graduate School form (https://gradschool.unh.edu/academics/forms-policies) .

### Annual Progress Report and Review Meeting
Each student will meet with a representative of the Graduate Program Committee in the spring semester to review progress and identify any concerns. The purpose of this meeting is to:

1) Encourage the student to think critically about his/her own progress (or lack thereof) and goals for both the immediate and long-term future.

2) Increase a sense of accountability on behalf of graduate students, and motivate students moving at a slow pace to increase their productivity and involvement in the program.

3) Remind students that to be a truly successful graduate student, one should (ideally) demonstrate success in multiple areas (research, funding, teaching, service), and provide examples for how to do that.

4) Provide a clear paper trail in case situations arise in which there is confusion or disagreement about a student's progress.

The annual meeting also provides an opportunity for students to raise any concerns, and provide feedback about the program and their graduate experience.

In preparation for progress review meetings, 
• The student writes a report about their progress, and submits it to their advisor and committee for review and comments. This should occur in the first half of the spring semester. Instructions and template for the student report are available at the program website, or from the department. 
• The advisor reviews and signs the student’s report, and then also fills out an evaluation describing his/her view of the student's progress, and including a summary of the most recent committee meeting – which should take place earlier in the same semester. Instructions and template for the advisor report are available at the program website, or from the department. Reports must be submitted at least one week before scheduled meetings, normally by mid-April.
• Instructors for whom the student has served as a teaching assistant provide comments on their teaching. (If instructors have previously provided feedback as part of fellowship or other applications, they needn’t do so again.) Comments must be submitted at least one week before scheduled meetings, normally by mid-April.

All reports and comments will be submitted to the designated departmental staff person, who will schedule a review meeting for each student with a member of the GPC (not including the advisor or, preferably, other members of the student’s committee), normally between mid-April and mid-May. 

Following the meetings, comments and suggestions will be shared with the student and advisor, as well as the Program Coordinator. If there is material in the comments that is confidential or should not be shared, it may be withheld at the discretion of the Program Coordinator.

Students who do not complete the review process by the specified date will have a hold placed on their registration by the Graduate School until they have resolved the situation.

### Completing the Degree

As a graduate student, you are responsible for knowing what you need to do to get your degree: your advisor and committee should offer guidance, but the primary responsibility is yours. Make sure you are thoroughly familiar with:

• the program’s academic requirements (credits, courses, competencies);
• necessary paperwork (committee nomination, Ph.D. candidacy, etc.);
• thesis/dissertation format and filing requirements (set by the Graduate School);
• format and scheduling procedures for qualifying exams and thesis/dissertation defense; and all relevant deadlines.

If you have questions about what you need to do, or how to do it, consult your advisor, the Program Coordinator, and/or the UNH Graduate School. If there is information you think needs to be added or clarified in this handbook, please tell the Program Coordinator.

For both the MS thesis and Ph.D. dissertation students are required to give a public, advertised seminar on the UNH campus, followed by a private examination by the student's committee, which may require revisions. The committee is responsible for assessing and approving the final version of the thesis. The committee should be provided with a complete copy of the thesis for review at least two full weeks before the defense.

The student is responsible for transmitting necessary paperwork to the Graduate School, and fulfilling Graduate School requirements for electronic submission of the thesis, by the appropriate deadline.


### Graduation

The Graduate School website provides detailed information on graduation procedures, including deadlines, filing “intent to graduate” notification, submitting theses/dissertations to the Graduate School, and Commencement: http://www.gradschool.unh.edu/graduation.php

### Student Rights and Key Policies

UNH’s statement on Student Rights, Rules, and Responsibilities applies to graduate students as well as to undergraduates. It can be found at https://catalog.unh.edu/srrr/ 
See Graduate School Catalog for general information, policies, and student rights: https://catalog.unh.edu/graduate/
